#!/bin/bash
#
# setup.sh - Auto-configure Makefile for PMM emulator programs
#
# Automatically detects:
# - OS (macOS vs Linux)
# - GPU/CUDA availability
# - Library paths (OpenBLAS, CUDA, etc.)
#
# Usage: ./setup.sh
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
echo_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
echo_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"

# Global variables
HAS_GPU=false
CUDA_PATH=""
OPENBLAS_DIR=""
OS_TYPE=""

# Detect OS
detect_os() {
    if [[ "$OSTYPE" == "darwin"* ]]; then
        OS_TYPE="macos"
    elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
        OS_TYPE="linux"
    else
        OS_TYPE="unknown"
    fi
    echo_info "OS detected: $OS_TYPE"
}

# Detect GPU and CUDA
detect_gpu() {
    if command -v nvidia-smi &> /dev/null; then
        GPU_INFO=$(nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null || true)
        if [ -n "$GPU_INFO" ]; then
            echo_info "NVIDIA GPU detected: $GPU_INFO"
            HAS_GPU=true

            # Find CUDA
            for path in /usr/local/cuda /usr/local/cuda-12 /usr/local/cuda-11 /opt/cuda; do
                if [ -d "$path" ] && [ -f "$path/bin/nvcc" ]; then
                    CUDA_PATH="$path"
                    echo_info "CUDA found at: $CUDA_PATH"
                    break
                fi
            done

            if [ -z "$CUDA_PATH" ] && command -v nvcc &> /dev/null; then
                CUDA_PATH=$(dirname $(dirname $(which nvcc)))
                echo_info "CUDA found via PATH: $CUDA_PATH"
            fi

            return 0
        fi
    fi

    echo_info "No NVIDIA GPU detected, will use CPU only"
    HAS_GPU=false
    return 1
}

# Find OpenBLAS
find_openblas() {
    # macOS paths
    if [[ "$OS_TYPE" == "macos" ]]; then
        if [[ $(uname -m) == "arm64" ]]; then
            OPENBLAS_DIR="/opt/homebrew/opt/openblas"
        else
            OPENBLAS_DIR="/usr/local/opt/openblas"
        fi
        if [ -d "$OPENBLAS_DIR" ]; then
            echo_info "OpenBLAS found at: $OPENBLAS_DIR"
            return 0
        fi
    fi

    # Linux paths
    for path in /usr/lib/x86_64-linux-gnu /usr/lib64 /usr/lib /usr/local/lib; do
        if [ -f "$path/libopenblas.so" ] || [ -f "$path/libopenblas.a" ]; then
            OPENBLAS_DIR=$(dirname "$path")
            echo_info "OpenBLAS found at: $OPENBLAS_DIR"
            return 0
        fi
    done

    # Check ldconfig on Linux
    if command -v ldconfig &> /dev/null; then
        if ldconfig -p | grep -q libopenblas; then
            OPENBLAS_DIR="/usr"
            echo_info "OpenBLAS found via ldconfig"
            return 0
        fi
    fi

    echo_warn "OpenBLAS not found, will use standard BLAS/LAPACK"
    OPENBLAS_DIR="/usr"
    return 1
}

# Generate Makefile
generate_makefile() {
    local MAKEFILE="$SCRIPT_DIR/Makefile"
    local MAKEFILE_BAK="$SCRIPT_DIR/Makefile.bak"

    # Backup existing Makefile
    if [ -f "$MAKEFILE" ]; then
        cp "$MAKEFILE" "$MAKEFILE_BAK"
        echo_info "Backed up existing Makefile"
    fi

    echo_info "Generating Makefile..."

    # Build library paths based on OS and GPU
    if [[ "$OS_TYPE" == "macos" ]]; then
        LIBS_LINE="LIBS = -L.. -lcookie \\
       -L../../general_modules -lgeneralmodules \\
       -L../../pw_modules -lpwmodules \\
       -L../../mesh_modules -lmeshmodules \\
       -L../../pot_modules -lpotmodules \\
       -L${OPENBLAS_DIR}/lib -lopenblas \\
       -lblas -llapack -fopenmp"
    else
        # Linux
        if $HAS_GPU && [ -n "$CUDA_PATH" ]; then
            LIBS_LINE="LIBS = -L.. -lcookie \\
       -L../../general_modules -lgeneralmodules \\
       -L../../pw_modules -lpwmodules \\
       -L../../mesh_modules -lmeshmodules \\
       -L../../pot_modules -lpotmodules \\
       -L${CUDA_PATH}/lib64 -lcusolver -lcublas -lcudart \\
       -lopenblas -lblas -llapack -fopenmp -lstdc++"
        else
            LIBS_LINE="LIBS = -L.. -lcookie \\
       -L../../general_modules -lgeneralmodules \\
       -L../../pw_modules -lpwmodules \\
       -L../../mesh_modules -lmeshmodules \\
       -L../../pot_modules -lpotmodules \\
       -lopenblas -lblas -llapack -fopenmp"
        fi
    fi

    cat > "$MAKEFILE" << EOF
# Makefile for PMM (Parametric Model Manager) emulator programs
# Auto-generated by setup.sh on $(date)
# OS: $OS_TYPE, GPU: $HAS_GPU

FC = gfortran
FFLAGS = -fPIC -fopenmp -O3 -ffree-line-length-0

# Include paths
INCS = -I.. -I../../general_modules -I../../mesh_modules -I../../pw_modules -I../../pot_modules

# Library paths
$LIBS_LINE

# Module objects
MODS = emulator_io.o param_mapping.o

# Targets
all: emulator_train emulator_predict

# Module compilation
emulator_io.o: emulator_io.F90
	\$(FC) \$(FFLAGS) \$(INCS) -c \$<

param_mapping.o: param_mapping.F90
	\$(FC) \$(FFLAGS) \$(INCS) -c \$<

# Training program
emulator_train: emulator_train.F90 \$(MODS)
	\$(FC) \$(FFLAGS) \$(INCS) -o \$@ \$< \$(MODS) \$(LIBS)

# Prediction program
emulator_predict: emulator_predict.F90 \$(MODS)
	\$(FC) \$(FFLAGS) \$(INCS) -o \$@ \$< \$(MODS) \$(LIBS)

# Test programs
test_multiJ_accuracy: test_multiJ_accuracy.F90 \$(MODS)
	\$(FC) \$(FFLAGS) \$(INCS) -o \$@ \$< \$(MODS) \$(LIBS)

test_multiJ_prediction: test_multiJ_prediction.F90 \$(MODS)
	\$(FC) \$(FFLAGS) \$(INCS) -o \$@ \$< \$(MODS) \$(LIBS)

test_multiJ_reconstruction: test_multiJ_reconstruction.F90 \$(MODS)
	\$(FC) \$(FFLAGS) \$(INCS) -o \$@ \$< \$(MODS) \$(LIBS)

clean:
	rm -f emulator_train emulator_predict test_multiJ_* *.o *.mod

.PHONY: all clean
EOF

    echo_info "Makefile generated successfully!"
}

# Print summary
print_summary() {
    echo ""
    echo "=========================================="
    echo "  PMM Setup Summary"
    echo "=========================================="
    echo "OS:        $OS_TYPE"
    echo "GPU:       $HAS_GPU"
    if $HAS_GPU; then
        echo "CUDA:      $CUDA_PATH"
    fi
    echo "OpenBLAS:  $OPENBLAS_DIR"
    echo ""
    echo "Next steps:"
    echo "  1. Build cookie library first:"
    echo "     cd $ROOT_DIR/cookie && make"
    echo "  2. Build pmm programs:"
    echo "     cd $SCRIPT_DIR && make"
    echo "=========================================="
}

# Main
main() {
    echo "=========================================="
    echo "  PMM Emulator Setup Script"
    echo "=========================================="

    detect_os
    detect_gpu || true
    find_openblas || true
    generate_makefile
    print_summary

    echo_info "Setup complete!"
}

main "$@"
